config/routes.rb
Cookbook::Application.routes.draw do
  resources :recipes do
    member do
      get 'ingredients'
    end
  end
  resources :ingredients

  root :to => 'recipes#index'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :measurements
  has_many :recipes, :through => :measurement

  validates :name, :presence => true
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
  accepts_nested_attributes_for :ingredient

  validates :ingredient_size, :presence => true

  def ingredient_name
    ingredient && ingredient.name
  end

  def ingredient_name=(name)
    self.ingredient = Ingredient.find_or_create_by_name(name) unless name.blank?
  end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :measurements
  has_many :ingredients, -> {uniq}, :through => :measurements
  accepts_nested_attributes_for :ingredients  #### try removing this
  accepts_nested_attributes_for :measurements
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ingredient }
      else
        format.html { render action: 'new' }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :lactose, :nut, :shellfish, :wheat, :vegetarian, :vegan)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @measurements = @recipe.measurements.build
#    @ingredients = @recipe.measurements.build.build_ingredient

  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    binding.pry
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :type, :servings, :directions,
        :measurements_attributes => [:id, :ingredient_size, :ingredient_unit,
            :ingredient_name
 #         :ingredient_attributes => [:id, :name]
          ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lactose %><br>
    <%= f.check_box :lactose %>
  </div>
  <div class="field">
    <%= f.label :nut %><br>
    <%= f.check_box :nut %>
  </div>
  <div class="field">
    <%= f.label :shellfish %><br>
    <%= f.check_box :shellfish %>
  </div>
  <div class="field">
    <%= f.label :wheat %><br>
    <%= f.check_box :wheat %>
  </div>
  <div class="field">
    <%= f.label :vegetarian %><br>
    <%= f.check_box :vegetarian %>
  </div>
  <div class="field">
    <%= f.label :vegan %><br>
    <%= f.check_box :vegan %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Ingredient Allergies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lactose</th>
      <th>Nut</th>
      <th>Shellfish</th>
      <th>Wheat</th>
      <th>Vegetarian</th>
      <th>Vegan</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.lactose ? 'x' : '' %></td>
        <td><%= ingredient.nut ? 'x' : '' %></td>
        <td><%= ingredient.shellfish ? 'x' : '' %></td>
        <td><%= ingredient.wheat ? 'x' : ''%></td>
        <td><%= ingredient.vegetarian ? 'x' : '' %></td>
        <td><%= ingredient.vegan ? 'x' : '' %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Remove', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %><br>
<%= link_to 'Back to Recipes', recipes_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<h1>Ingredient</h1>

<h2><%= @ingredient.name %></h2>

<h3>Properties:</h3>
<p>
<%= @ingredient.lactose ? 'Lactose' : '' %>
<%= @ingredient.nut ? 'Nut' : '' %>
<%= @ingredient.shellfish ? 'Shellfish' : '' %>
<%= @ingredient.wheat ? 'Wheat' : '' %>
<%= @ingredient.vegetarian ? 'Vegetarian' : '' %>
<%= @ingredient.vegan ? 'Vegan' : '' %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back to Ingredients List', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :value => "Chocolate Chip Cookies" %>
  </div>
  <div class="field">
    <%= f.label :servings %><br>
    <%= f.text_field :servings, :value => 4 %>
  </div>

  <h2>Ingredients</h2>
  <div class="items">
    <%= f.nested_fields_for :measurements do |m| %>

      <fieldset class="item">
        <%= m.text_field :ingredient_size, :value => 1, :size => 5 %>
        <%= m.select :ingredient_unit, %w[unit tbsp tsp cup pint quart oz] %>
        <%= m.text_field :ingredient_name %>

        <a href="#" class="remove">Remove</a>
        <%= m.hidden_field :id %>
        <%= m.hidden_field :_destroy %>
      </fieldset>

    <% end %>
  </div>
  <a href="#" class="add">Add</a>

  <div class="field">
    <%= f.label :directions %><br>
    <%= f.text_area :directions, :size => '50x10' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Cookbook Recipes</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to recipe.name, recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Remove', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %><br>
<%= link_to 'View Ingredients Properties', ingredients_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Servings:</strong>
  <%= @recipe.servings %>
</p>

<p>
  <strong>Ingredients:</strong><br>
    <% @recipe.measurements.each do |m| %>
      <%= m.ingredient_size %>
      <%= m.ingredient_unit %>
      <%= m.ingredient.name %>
      <br>
    <% end %>
</p>

<p>
  <strong>Directions:</strong>
  <%= @recipe.directions %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>